apiVersion: v1
kind: Pod
metadata:
  name: pod-in-default-namespace
  namespace: default
  labels:
    app: insecure-kubernetes-workloads
spec:
  automountServiceAccountToken: true
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80