apiVersion: apps/v1
kind: Deployment
metadata:
  name: root-user-nginx-deployment
  namespace: insecure-kubernetes-workloads
spec:
  selector:
    matchLabels:
      app: root-user-nginx-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: root-user-nginx-deployment
    spec:
      containers:
      - name: root-user-nginx-deployment
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      securityContext:
        runAsUser: 0
    
