apiVersion: v1
kind: Service
metadata:
  name: service-using-nodeport
  namespace: insecure-kubernetes-workloads
spec:
  type: NodePort
  selector:
    app: root-user-nginx-deployment
  ports:
    - port: 80
      targetPort: 80