apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: insecure-kubernetes-workloads
  name: unrestricted-api-access-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
